### ISSUE TITLE
NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by madpsy** [ngoduykhanh/PowerDNS-Admin#194]
After performing a 'git pull' (by accident I must admit), for some reason pdns-admin broke.

This occurs if if run directly (./run.py) or via wsgi. It was working beforehand so not sure what could have gone wrong here.

Anyone any thoughts?

`Traceback (most recent call last):
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask_login/utils.py", line 227, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask_login/login_manager.py", line 148, in unauthorized
    return self.unauthorized_callback()
  File "/var/www/pdns-admin/app/views.py", line 201, in login
    basic_enabled=BASIC_ENABLED, signup_enabled=SIGNUP_ENABLED)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/var/www/pdns-admin/flask/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/var/www/pdns-admin/app/views.py", line 65, in inject_auto_ptr_setting
    return dict(auto_ptr_setting=strtobool(auto_ptr_setting.value))
AttributeError: 'NoneType' object has no attribute 'value'`

**Comment by cgonzalez** [comment]
I have the same issue. Have to use a backup of the application to recover.

What additional details can I send you to diagnose this problem?

**Comment by fabiorauber** [comment]
Just updated to the latest version, and the application broke with the same error:

```
[2017-09-04 12:14:54,851] ERROR in app: Exception on /error/500 [GET]
pdnsadmin_1  | Traceback (most recent call last):
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
pdnsadmin_1  |     response = self.full_dispatch_request()
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
pdnsadmin_1  |     rv = self.handle_user_exception(e)
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
pdnsadmin_1  |     reraise(exc_type, exc_value, tb)
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
pdnsadmin_1  |     rv = self.dispatch_request()
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
pdnsadmin_1  |     return self.view_functions[rule.endpoint](**req.view_args)
pdnsadmin_1  |   File "/opt/pdnsadmin/app/views.py", line 151, in error
pdnsadmin_1  |     return render_template('errors/%s.html' % code, msg=msg), int(code)
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/templating.py", line 132, in render_template
pdnsadmin_1  |     ctx.app.update_template_context(context)
pdnsadmin_1  |   File "/opt/pdnsadmin/flask/local/lib/python2.7/site-packages/flask/app.py", line 764, in update_template_context
pdnsadmin_1  |     context.update(func())
pdnsadmin_1  |   File "/opt/pdnsadmin/app/views.py", line 65, in inject_auto_ptr_setting
pdnsadmin_1  |     return dict(auto_ptr_setting=strtobool(auto_ptr_setting.value))
pdnsadmin_1  | AttributeError: 'NoneType' object has no attribute 'value'

```

**Comment by fabiorauber** [comment]
This problem is similar of the one in the issue https://github.com/ngoduykhanh/PowerDNS-Admin/issues/51. Solved by inserting auto_ptr setting in database:

```
insert into setting(name,value) values ('auto_ptr', 'False');
```

**Comment by madpsy** [comment]
@fabiorauber  - Excellent thanks! That is indeed the fix for this one.

**Comment by thomasDOTde** [comment]
fixed the application to handle null-values:
https://github.com/thomasDOTde/PowerDNS-Admin/commit/65736df7ad9de2c055db36f868567b0bf65c9932

**Comment by ngoduykhanh** [comment]
Thanks for raising the issue. Did the same fix as @thomasDOTde .

**Comment by izenk** [comment]
+1 Issue still persist
Latest pull on master(0fb6e10cf5d65e2cbba89e5cdf915a68102006be)

**Comment by tmuncks** [comment]
The same solution that was applied to `inject_auto_ptr_setting` should be applied to the rest of the `inject_*` functions.

**Comment by tmuncks** [comment]
But this is only ever relevant, if the settings table for some reason gets truncated, as I see it?

**Comment by izenk** [comment]
Error happened during after installation - first app run.
I followed: [Running-PowerDNS-Admin-on-Ubuntu-16.04](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-on-Ubuntu-16.04---Ubuntu-18.04)

I found another way described here [PowerDNS-Admin-in-Fedora-23](https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Install-PowerDNS-Admin-in-Fedora-23) - and it works.
So, may be just obsolete info in section for Ubuntu.
